#!/bin/sh
# /etc/init.d/tvonline

### BEGIN INIT INFO
# Provides: tvonline
# Required-Start: $remote_fs
# Required-Stop: $remote_fs
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start the TVOnlineWeb server
# Description: TVOnline is a program that serves video streams
### END INIT INFO

cd /home/pi/tvonline
case "$1" in
  start)
    echo "Starting tvOnline"
    nohup python tvOnlineWeb.py > log.txt 2>&1 &
    PID=$!
    GPID=`ps x -o "%p %r" | grep ${PID} | sed -e 's/^ \w*\ *//'`
    echo ${GPID} > gpid.txt
    ;;
  stop)
    echo "Stopping tvOnline"
    GPID=`cat gpid.txt`
    kill -9 -${GPID}
    ;;
  *)
    echo "Usage: /etc/init.d/tvonline {start|stop}"
    exit 1
    ;;
esac

exit 0

